wb-utils (1.03) stable; urgency=medium
  * Add restart_if_broken command line argument to wb-gsm:
  *  test if modem answers to AT command and if it doesn't then
  *  perform power restart cycle

diff --git a/utils/gsm/wb-gsm b/utils/gsm/wb-gsm
--- a/utils/gsm/wb-gsm
+++ b/utils/gsm/wb-gsm
@@ -164,6 +164,19 @@ function ensure_on() {
 	set_speed
 }
 
+function restart_if_broken() {
+    #~ set_speed
+    /usr/sbin/chat   TIMEOUT 5 ABORT "ERROR" ABORT "BUSY" "" ATZ OK "" > $PORT < $PORT
+    RC=$?
+
+    if [[ $RC != 0 ]] ; then
+        debug "connection test error!"
+        debug "Restarting GSM modem..."
+        ensure_on
+        sleep 5
+        exit $RC;
+    fi
+}
 init
 
 
@@ -180,6 +193,10 @@ case "$1" in
 	"on" )
 		ensure_on
 	;;
+
+    "restart_if_broken" )
+        restart_if_broken
+    ;;
 
 	"off" )
 		switch_off
