initramfs: WB7 update support
  * add boards/7x.sh and boards/7-usbgadget.sh files
  * initramfs: add libupdate.wb7.sh
  * add dosfstools to initramfs
  * implement update from microsd
  * explicitly set direction for gpio
  * Presence of USB gadget is detected by new usb_role class api
  * Drop to debug console on errors
  * Do not try to perform factory reset from factory fit if media with update is present
  * initramfs: create proper partition table on ramdisk so Windows can handle it

diff --git a/initramfs/files/init b/initramfs/files/init
--- a/initramfs/files/init
+++ b/initramfs/files/init
@@ -1,6 +1,26 @@
 #!/bin/busybox sh
 /bin/busybox --install -s
 
+led() {
+	echo "$3" > "/sys/class/leds/$1/$2" 2>/dev/null || true
+}
+
+
+start_debug_console() {
+	umount /disk >/dev/null 2>&1 || true
+	umount /usb >/dev/null 2>&1 || true
+
+	led red trigger none
+	led red brightness 255
+	led green trigger none
+	led green brightness 0
+
+	TTY=/dev/console
+	exec setsid sh -c "exec sh <$TTY >$TTY 2>&1"
+}
+
+trap 'start_debug_console' EXIT
+
 /bin/mknod /dev/null c 1 3
 /bin/mknod /dev/tty c 5 0
 
@@ -14,6 +34,7 @@ mkdir -p /dev/shm
 mkdir -p /var/lock
 
 EMMC=/dev/mmcblk0
+MICROSD=/dev/mmcblk1
 RAMDISK="/tmp/ramdisk.img"
 ALLOWED_FIT_NAMES="wb_update.fit wb6_update.fit wb_update_FACTORYRESET.fit wb6_update_FACTORYRESET.fit"
 USBDIR="/usb"
@@ -24,6 +45,7 @@ echo "Boot mode: $BOOTMODE"
 
 BOARD_FAMILY="wb6"
 DT_COMPAT_LIST=`tr < /proc/device-tree/compatible  '\000' '\n'`
+
 
 for compat in $DT_COMPAT_LIST; do
 	case "$compat" in
@@ -44,10 +66,6 @@ for compat in $DT_COMPAT_LIST; do
 done
 
 depmod
-
-led() {
-	echo "$3" > "/sys/class/leds/$1/$2" 2>/dev/null || true
-}
 
 set_led_update_in_progress() {
 	led red trigger none
@@ -95,6 +113,21 @@ search_for_usb_drive() {
 	ls /dev/sd* >/dev/null 2>&1
 }
 
+search_for_sd() {
+	local SD_SETTLE_TIME=3
+	local COUNT=0
+	while [[ ! -e ${MICROSD}p1 && $COUNT -lt $SD_SETTLE_TIME ]]; do
+		echo -ne "Waiting for microSD to settle ($((COUNT+1))/$SD_SETTLE_TIME)\\r"
+		sleep 1
+		let COUNT++
+	done
+	echo
+
+	# Look for any partitions on sd card
+	ls ${MICROSD}p* >/dev/null 2>&1
+}
+
+
 # Search for .fit files in a given directory and run update
 #
 # @param $1 directory to look for .fit files
@@ -111,7 +144,7 @@ update_from_fs() {
 		if [[ -e "${FIT}" ]]; then
 			if [[ ! -z "${FOUND_FIT_NAME}" ]]; then
 				echo "ERROR: multiple .fit found on ${SOURCE} (${DIR}): ${FOUND_FIT_NAME} and ${FNAME}. Leave just one from a list: ${FIT_NAMES}"
-				exit 1
+				exit
 			fi
 
 			FOUND_FIT_NAME="$FNAME"
@@ -129,7 +162,7 @@ update_from_fs() {
 			local result=$?
 			if [[ $result != 0 ]]; then
 				echo "ERROR: update is not confirmed, exiting"
-				exit 1
+				exit
 			fi
 		fi
 
@@ -141,29 +174,32 @@ update_from_fs() {
 	
 }
 
-# @param $1 .fit filename. If blank, look for all possible file names
-update_from_usb_drive() {
-	local FIT_NAME="$1"
+
+
+# @param $1 block device path spec
+# @param $2 .fit filename. If blank, look for all possible file names
+# @param $3 human-readable source name 
+update_from_block_device() {
+	local PATHSPEC="$1"
+	local FIT_NAME="$2"
+	local SOURCE_NAME="$3"
+	local BLOCKDIR=/disk
 	if [[ -z "${FIT_NAME}" ]]; then
 		local FIT_NAMES="${ALLOWED_FIT_NAMES}"
 	else
 		local FIT_NAMES="${FIT_NAME}"
 	fi
 
-	mkdir -p "$USBDIR"
+	mkdir -p "$BLOCKDIR"
 
-	for USBDEV in /dev/sd*; do
-		echo "Looking for update .fit on ${USBDEV}..."
+	for BLOCKDEV in ${PATHSPEC}; do
+		echo "Looking for update .fit on ${BLOCKDEV}..."
 
-		umount "$USBDIR" >/dev/null 2>&1 || true
-		mount -t auto "$USBDEV" "$USBDIR" >/dev/null 2>&1 || continue
-		cleanup() {
-			umount "$USBDIR"
-		}
-		trap cleanup EXIT
-
-		update_from_fs "${USBDIR}" "${FIT_NAMES}" "USB drive"
+		umount "$BLOCKDIR" >/dev/null 2>&1 || true
+		mount -t auto "$BLOCKDEV" "$BLOCKDIR" >/dev/null 2>&1 || continue
+		update_from_fs "${BLOCKDIR}" "${FIT_NAMES}" "${SOURCE_NAME}"
 	done
+	return 1
 }
 
 wait_for_emmc() {
@@ -193,43 +229,72 @@ update_from_emmc() {
 }
 
 update_from_gadget() {
-	mount -t vfat ${RAMDISK} /usb
+	modprobe -r g_mass_storage
+	mkdir -p "$USBDIR"
+	losetup -o 1048576 /dev/loop0 ${RAMDISK}
+	mount -t vfat /dev/loop0 "$USBDIR"
 	echo "Will look for update in USB gadget ramdisk"
-	update_from_fs /usb "${ALLOWED_FIT_NAMES}" "USB gadget"
+	update_from_fs "$USBDIR" "${ALLOWED_FIT_NAMES}" "USB gadget" ||
+		echo "ERROR: No update .fit uploaded to virtual USB drive!!"
 }
 
 check_usb_gadget_connected() {
-	#TODO
-	true
-}
-
-wait_usb_gadget_connected() {
-	[[ "${BOARD_FAMILY}" == "wb7" ]] && {
-		local WAIT_GADGET_TIME=3
-		local COUNT=0
-		while ! check_usb_gadget_connected && [[ $COUNT -lt $WAIT_GADGET_TIME ]]; do
-			echo -ne "Waiting for USB gadget to connect to host PC ($(($COUNT+1))/$WAIT_GADGET_TIME)\\r"
-			sleep 1
-			let COUNT++
-		done
-		echo
-		check_usb_gadget_connected
-	}
+	[[ "x$(cat /sys/class/udc/*/current_speed)" != "xUNKNOWN" ]]
 }
 
 wait_for_gadget_disconnect() {
-	#TODO
-	sleep 10
-	true
+	local COUNT=0
+	while check_usb_gadget_connected; do
+		echo -ne "Copy .fit file to virtual USB driver and unplug the cable ($(($COUNT+1)))\\r"
+		sleep 1
+		let COUNT++
+	done
+	echo
+	! check_usb_gadget_connected
+}
+
+check_usb_gadget_cable_present() {
+	[[ "x$(cat /sys/class/usb_role/*/role)" == "xdevice" ]]
+}
+
+force_enable_usb_host() {
+	# on Wiren Board 7 there is a mux between usb-c peripheral connector and usb-a host connector
+	# the mux is automatically switched to peripheral connector if there is a cable there
+	# but we can force the mux to USB-A instead
+
+	for switch in /sys/class/usb_role/*/role ; do
+		echo "host" > $switch
+	done
+
+	return 0
+}
+
+wait_usb_gadget_connected() {
+	local WAIT_GADGET_TIME=7
+	local COUNT=0
+	while ! check_usb_gadget_connected && [[ $COUNT -lt $WAIT_GADGET_TIME ]]; do
+		echo -ne "Waiting for USB gadget to connect to host PC ($(($COUNT+1))/$WAIT_GADGET_TIME)\\r"
+		sleep 1
+		let COUNT++
+	done
+	echo
+	check_usb_gadget_connected
+}
+
+is_usb_gadget_supported() {
+	[[ "${BOARD_FAMILY}" == "wb7" ]]
 }
 
 setup_usb_ram_mass_storage() {
 		# create usb_mass_storage first
-		dd if=/dev/zero of=${RAMDISK} bs=1M count=300
-		mkfs.vfat ${RAMDISK}
-		mount -t vfat ${RAMDISK} /usb
-		cp /usr/share/README.ramdisk.txt /usb/README.txt
-		umount /usb
+		dd if=/dev/zero of=${RAMDISK} bs=1M count=300  >/dev/null 2>&1
+		echo ",,b" | sfdisk ${RAMDISK}
+		losetup -o 1048576 /dev/loop0 ${RAMDISK}
+		mkfs.vfat /dev/loop0
+		mkdir -p "$USBDIR"
+		mount -t vfat /dev/loop0 "$USBDIR"
+		cp /usr/share/README.ramdisk.txt "${USBDIR}/README.txt"
+		umount "$USBDIR"
 
 		echo "Activate Mass Storage device"
 		modprobe g_mass_storage file=${RAMDISK} iManufacturer="Wiren Board" iProduct="Wiren Board RAM disk"
@@ -244,22 +309,44 @@ setup_usb_ssh() {
 
 case "$BOOTMODE" in
 	update_auto)
-		if search_for_usb_drive; then
-			CONFIRM=y update_from_usb_drive
-		elif wait_usb_gadget_connected; then
-			setup_usb_ram_mass_storage &
+		local enable_emmc_update="y"
+
+		is_usb_gadget_supported && setup_usb_ram_mass_storage
+
+		if is_usb_gadget_supported && check_usb_gadget_cable_present && wait_usb_gadget_connected; then
+			enable_emmc_update="n"
 			wait_for_gadget_disconnect
-			CONFIRM=y update_from_gadget
-		else
+			update_from_gadget
+		fi
+
+		if force_enable_usb_host && search_for_usb_drive; then
+			enable_emmc_update="n"
+			CONFIRM=y update_from_block_device "/dev/sd*" "" "USB Flash Drive"
+		fi
+
+		if search_for_sd; then
+			enable_emmc_update="n"
+			CONFIRM=y update_from_block_device "${MICROSD}p*" "" "microSD card"
+		fi
+
+		if [[ "x${enable_emmc_update}" == "xy" ]]; then
 			update_from_emmc
 		fi
+
 		;;
 	usbupdate*)
 		FIT_NAME="${BOOTMODE#*,}"
-		[[ "${FIT_NAME}" == "usbupdate" ]] && FIT_NAME="update.fit"
+		[[ "${FIT_NAME}" == "usbupdate" ]] && FIT_NAME="wb_update.fit"
 
 		search_for_usb_drive &&
 			update_from_usb_drive ${FIT_NAME}
+		;;
+	sdupdate*)
+		FIT_NAME="${BOOTMODE#*,}"
+		[[ "${FIT_NAME}" == "sdupdate" ]] && FIT_NAME="wb_update.fit"
+
+		search_for_sd &&
+			update_from_block_device "${MICROSD}p*" " ${FIT_NAME}" "microSD card"
 		;;
 	usbgadget|*)
 		FLAG=/flag
@@ -284,6 +371,6 @@ case "$BOOTMODE" in
 		;;
 esac
 
-# for debugging
-TTY=$(sed -rn 's#.*console=(tty[a-zA-Z0-9]*).*#/dev/\1#p' /proc/cmdline)
-exec setsid sh -c "exec sh <$TTY >$TTY 2>&1"
+
+sleep 1
+start_debug_console
